name: CI for algorithm package

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "algorithm/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/**"
      - "algorithm/**"

jobs:
  ci:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: algorithm
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Downlaod Go packages
        run: go mod download
        env:
          GOPROXY: "https://proxy.golang.org"
      - name: Test Go codes
        run: go test ./...
        env:
          GOPROXY: "https://proxy.golang.org"
